"""
CSAPX Lab 1: L-system drawing generator

A program that combines a string rewriting L-system and an interpreter
to generate 2D drawings using the 2D turtle graphics library.

author: Colin Rindge
CSAPX - Strout
"""
import turtle

def main() -> None:
    """
    The main loop responsible for getting the input details from the user,
    printing in the standard output the resulting string generated by the L-system
    and drawing its graphical representation
    :return: None
    """
    axiom = input('Input Axiom: ')
    num_prod_rules = int(input('Input Number of Production Rules: '))
    prod_rules = []
    for i in range(num_prod_rules):
        prod_rules.append(input('Input Rule #' + str(i) + ': '))
    angle = int(input('Input Angle for Rotation: '))
    length = float(input('Input Length of Initial Line Segment: '))
    heading = int(input('Input Initial Heading (0-360): '))
    num_steps = int(input('Input Number of Steps: '))

    lsystem = apply_lsystem(axiom, prod_rules, num_steps)
    print(lsystem, length, angle)
    draw(lsystem, length, angle, heading)


def apply_lsystem(str1, prod_rules, num_steps):
    """
    :param str1: string to apply rules to
    :param prod_rules: list of rules
    :param num_steps: # of times to apply rules
    :return: String with rules applied num_steps time to axiom
    """
    new_str = ''
    for k in range(num_steps-1):
        for i in range(len(str1)):
            new_str += find_rule(str1[i], prod_rules)
        str1 = new_str
        new_str = ''
    return str1
    

def find_rule(axiom, prod_rules):
    """
    :param axiom: single character string
    :param prod_rules: list of rules
    :return: string with rule for axiom
    """
    for r in prod_rules:
        if r[0] == axiom:
            return r[4:]
    return axiom

def draw(lsystem, distance, angle, heading):
    """
    :param lsystem: String of l system to be drawn
    :param distance: distance turtle moves on .forward
    :param angle: angle turtle turns at
    :param heading: initial heading of turtle
    :return: none
    """
    turtle.setheading(heading)
    saved_locations = [[]]
    for i in range(len(lsystem)):
        if lsystem[i] == 'F' or lsystem[i] == 'G':
            turtle.pendown()
            turtle.forward(distance)
            print('forward(' + str(distance) + ')')
        elif lsystem[i] == 'f':
            turtle.penup()
            print('penup()')
            turtle.forward(distance)
            print('forward(' + str(distance) + ')')
            turtle.pendown()
            print('pendown()')
        elif lsystem[i] == '+':
            turtle.left(angle)
            print('left(' + str(angle) + ')')
        elif lsystem[i] == '-':
            turtle.right(angle)
            print('right(' + str(angle) + ')')
        elif lsystem[i] == '[':
            saved_locations.append([turtle.xcor(), turtle.ycor(), turtle.heading(), turtle.pensize(), distance])
            print('Current Position Saved')
        elif lsystem[i] == ']':
            turtle.penup()
            last_index = saved_locations[len(saved_locations)-1]
            turtle.goto(last_index[0], last_index[1])
            turtle.setheading(last_index[2])
            turtle.pensize(last_index[3])
            distance = last_index[4]
            saved_locations.pop()
            turtle.pendown()
            print('Returned to Previous Save State')
        elif lsystem[i] == '@':
            mult = float(lsystem[i+1:i+5])
            distance = distance * mult
            print('Distance Changed to ' + str(distance))
            i += 4
        elif lsystem[i] == '#':
            if '0' <= lsystem[i+1:i+3] <= '99':
                turtle.pensize(int(lsystem[i+1:i+3]))
                print('Pen Size set to ' + lsystem[i+1:i+3])
                i +=2
            else:
                turtle.pensize(1)
                print('Pen Size set to 1')
    turtle.mainloop()


if __name__ == '__main__':
    main()